package gateway

import (
	"net/http"

	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/timestamppb"

	"github.com/pokt-network/path/observation"
)

const (
	// ***************************************
	// ** General HTTP Headers **
	// ***************************************

	// This UUID is generated by Envoy Proxy (GUARD) and passed to PATH via the HTTP headers.
	// Ref: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-request-id
	httpHeaderEnvoyTraceID = "X-Request-Id"

	// APIVersionPrefix is the prefix for the API version.
	// It is used and removed by the routing middleware.
	//
	// Example:
	//
	// 	/v1/{rest_path_1} -> /{rest_path_1}
	// 	/v1/{rest_path_1}/{rest_path_2} -> /{rest_path_1}/{rest_path_2}
	// 	/v1/{rest_path_1}/{rest_path_2}/... -> /{rest_path_1}/{rest_path_2}/...
	APIVersionPrefix = "/v1"

	// ***************************************
	// ** Grove Portal HTTP Headers **
	// TODO_TECHDEBT: Isolate all Portal (Grove specific) headers into a separate
	// package/file/directory to make it ultra clear how these work.
	// ***************************************

	// HttpHeaderPortalAccountID is the header key for the portal account ID.
	httpHeaderPortalAccountID = "Portal-Account-ID"

	// HttpHeaderPortalAppID is the header key for the portal app ID.
	//
	// It is also used by the routing middleware in `router.go` to ensure
	// the portal app ID is not present in the request path that is forwarded to
	// the service endpoint.
	//
	// Example:
	//
	//  /1a2b3c4d/path/segment -> /path/segment
	//  /1a2b3c4d/path -> /path
	HttpHeaderPortalAppID = "Portal-Application-ID"

	// Portal API Key HTTP header.
	HttpHeaderAuthorization = "Authorization"

	// ***************************************
	// ** Regional HTTP Headers & Constants **
	// ***************************************

	// Auth Region HTTP header.
	httpHeaderAuthRegion = "Auth-Region"
)

// ---------- User Requests ----------

// getUserRequestGatewayObservations returns gateway-level observations for an organic, i.e. from a user, request.
func getUserRequestGatewayObservations(httpReq *http.Request) *observation.GatewayObservations {
	return &observation.GatewayObservations{
		// Extract Request Authentication fields from HTTP headers.
		RequestAuth:  extractAuthObservationFromHTTPHeaders(httpReq),
		RequestType:  observation.RequestType_REQUEST_TYPE_ORGANIC,
		ReceivedTime: timestamppb.Now(),
	}
}

// extractAuthObservationFromHTTPHeaders extracts authentication information from HTTP headers
// and returns it as a RequestAuth observation object.
//
// Headers extracted:
// - Auth request ID
// - Auth region
// - Portal account ID
// - Portal application ID
func extractAuthObservationFromHTTPHeaders(httpReq *http.Request) *observation.RequestAuth {
	// Extract authentication Trace ID from headers
	traceID := getTraceID(httpReq)

	// Extract region information from headers
	region := httpReq.Header.Get(httpHeaderAuthRegion)

	// Extract portal credentials from headers
	portalAccountID := httpReq.Header.Get(httpHeaderPortalAccountID)
	portalApplicationID := httpReq.Header.Get(HttpHeaderPortalAppID)

	// Construct and return the RequestAuth object with extracted values
	return &observation.RequestAuth{
		TraceId: traceID,
		Region:  region,
		PortalCredentials: &observation.PortalCredentials{
			PortalAccountId:     portalAccountID,
			PortalApplicationId: portalApplicationID,
		},
	}
}

// getTraceID extracts the trace ID from the HTTP headers.
// If the trace ID is not set, it generates a new UUID.
func getTraceID(httpReq *http.Request) string {
	// If the trace ID is set in the header by Envoy, use it.
	if traceID := httpReq.Header.Get(httpHeaderEnvoyTraceID); traceID != "" {
		return traceID
	}

	// If the trace ID is not set, fallback to generating a new UUID.
	// This is a fallback for cases where the trace ID is not set by
	// Envoy. For example, if PATH is running standalone (i.e. not behind Envoy).
	return uuid.New().String()
}
